version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run: docker --version && node --version && npm --version