version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install
      - run:
          name: run tests
          command: npm test